I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\Superhero\Documents\Проект на Renpy\PMCgriffon\game/Fighter.rpy.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 400: invalid continuation byte

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\main.py", line 455, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\script.py", line 941, in load_appropriate_file
    data, stmts = self.load_file(dir, fn + source)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\script.py", line 721, in load_file
    stmts = renpy.parser.parse(fullfn)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\parser.py", line 1673, in parse
    lines = list_logical_lines(fn, filedata, linenumber)
  File "C:\Renpy\renpy-8.2.1-sdk\renpy\lexer.py", line 278, in list_logical_lines
    data = f.read().decode("utf-8", "python_strict")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 400: invalid continuation byte

Windows-10-10.0.19043 AMD64
Ren'Py 8.2.1.24030407
 
Tue Apr  2 18:06:34 2024
